### ISSUE TITLE
Rename family to trio

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-dictionary#28]
This is mainly for the genomic harmonization inputs - so need to know if there are cases outside of trios that need tracking for this purpose? If not, should rename to trio, if so can keep as family but need to understand what other relationships would need to be tracked?

cc @junjun-zhang @yuankunzhu @kmhernan

**Comment by allisonheath** [comment]
Going to go simple first with trio as that fits most of the data at the moment, need a wider discussion on what might be required for more general family phasing / joint genotyping and multi generations.

**Comment by kmhernan** [comment]
For ped files there is a concept of a `FAMID` to identify the family the sample belongs to, so that will be important for more complex families.
