### ISSUE TITLE
Simplify clinical nodes

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-dictionary#3]
Looking at the current clinical nodes for GDC:
https://gdc.cancer.gov/developers/gdc-data-model/gdc-data-model-components

Given the expected complexity of the KFs clinical data we're likely building something new to handle clinical/phenotype data. So I think we should pare this model down to a more limited set for the initial tracking of data. My initial suggestion would be:

- Keep demographic and diagnosis
- Remove follow-up, family history, exposure, treatment

One consideration is that we might need to submit to GDC before the new clinical data system is built. So another option may be to keep those nodes, but just limit them to required GDC fields.

And then we need to consider the required fields and if any of them don't make sense for structural birth defect cohorts to either make optional or nullable.

Thoughts? @dmiller15 @junjun-zhang

**Comment by dmiller15** [comment]
The diagnosis and demographic are definitely the most important out of the group but I would say the diagnosis node definitely needs cleanup. Many of the properties are ill-defined and slated for removal/enumeration restriction coming up in the GDC. Sticking with just the required might not be the best idea if we can come up with a better way to describe them.

Sort of tangentially related to the optional/nullable stuff, it might be worth considering making all fields at least a dual type with "null" to allow users to remove submitted entries.

**Comment by allisonheath** [comment]
Ok, definitely should remove / add any relevant enum restrictions as an easy first pass. And then sounds like we should go through the diagnosis elements a bit more closely (also in the context of structural birth defects versus cancer diagnoses).

**Comment by allisonheath** [comment]
Not sure why the commit didn't close out this issue.
