### ISSUE TITLE
Gather properties that are on all nodes under one definition

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-dictionary#32]
For example: https://github.com/allisonheath/fauxdictionary/blob/develop/schemas/_definitions.yaml#L61-L79

**Comment by dmiller15** [comment]
That example reminds me, do you want to rename `submitter_id`?

**Comment by allisonheath** [comment]
I think at this point trying to rename `submitter_id` would cause more problems/confusion?

However, I do wonder about removing `state` as a system property? 

@philloooo ?

**Comment by philloooo** [comment]
If we don't want to use the GDC release process we are probably fine removing the state as system property

**Comment by allisonheath** [comment]
@philloooo cool, and renaming `submitter_id` would have a wider impact, right?

**Comment by philloooo** [comment]
yeah there are more special handlings with submitter_id than state
