### ISSUE TITLE
Multiplicity on workflows needs expansion

### ISSUE THREAD

**Issue by dmiller15** [kids-first/kf-dictionary#4]
Current hot topic in the GDC is the multiplicity of many of the workflow nodes. A primary example would be the alignment_workflow which is in a one_to_many relationship with the submitted_aligned_reads meaning only one alignment workflow can exist for a set of aligned reads. I believe this was done back when the assumption existed that we would only have one harmonization workflow; but as time progresses this is an overly restrictive description. Reruns of the same workflow as well as newly created workflows will need to be able to exist in the graph simultaneously.

The simplest change is just to root out these one_to relationships and replace them with a many_to. However, if more complicated measures are desired this might fall into the realm of versioning issues.

**Comment by allisonheath** [comment]
Or another approach might be just keep the `submitted_*` files that we need to track for now and if we decide to start adding in the workflows, we can assess the current state of the GDC model at that time and either reincorporate or model separately?

**Comment by dmiller15** [comment]
Yes, I did that with BloodPAC because the data types were so different and we had no idea what the users wanted to do. I would agree its better to leave off for now if the downstream analysis is not a primary focus.

**Comment by allisonheath** [comment]
I think we should go with `many_to` for now, we might be testing out more than one alignment and would want to track that for now. Made #9 to address paring down the file/workflow nodes for the time being.

**Comment by dmiller15** [comment]
In terms of simplifying the workflows, perhaps we should look at removing the `alignment_cocleaning_workflow`. By making the `alignment_workflow` "less specific" we should be able to fold these two nodes together in a more meaningful way.

**Comment by allisonheath** [comment]
Need to use one of these phrases for you commits to auto close the issue on Github: https://help.github.com/articles/closing-issues-using-keywords/ (addresses doesn't work)
