### ISSUE TITLE
Fix up time related fields

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-dictionary#58]
- [x] Remove year-based fields, see: https://github.com/NCI-GDC/gdcdictionary/pull/194
- [x] Remove `days_to_birth` from demographic
- [x] Change `days_to_death` in demographic to `age_at_death`
- [x] Remove `days_to_death` in diagnosis
- [x] Change `days_to_last_follow_up` to `age_at_last_follow_up`
- [x] Change `days_to_last_known_disease_status` to `age_at_last_known_disease_status`

The age fields generally make more sense and the various days_to intervals can be calculated. We still want to collect the age in days.

**Comment by znatty22** [comment]
Looks good, I don't see any issues
